// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5_Ac3gmdHuUbhfuKcAdTgAbj98vlL8rg',
    appId: '1:1093723663496:web:256b2ebd59d719c758433d',
    messagingSenderId: '1093723663496',
    projectId: 'event-app-m-2025',
    authDomain: 'event-app-m-2025.firebaseapp.com',
    storageBucket: 'event-app-m-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLu5IigJAg8VtLVtdRGc1DRbo0TgowuY',
    appId: '1:1093723663496:android:c91ed5b1a8bc074458433d',
    messagingSenderId: '1093723663496',
    projectId: 'event-app-m-2025',
    storageBucket: 'event-app-m-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaC2PX--wj2txaXwhrSRoQa9bTK_S3Kpw',
    appId: '1:1093723663496:ios:94ce4cac1888d21358433d',
    messagingSenderId: '1093723663496',
    projectId: 'event-app-m-2025',
    storageBucket: 'event-app-m-2025.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaC2PX--wj2txaXwhrSRoQa9bTK_S3Kpw',
    appId: '1:1093723663496:ios:94ce4cac1888d21358433d',
    messagingSenderId: '1093723663496',
    projectId: 'event-app-m-2025',
    storageBucket: 'event-app-m-2025.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5_Ac3gmdHuUbhfuKcAdTgAbj98vlL8rg',
    appId: '1:1093723663496:web:1c19e0e9af7ab8a958433d',
    messagingSenderId: '1093723663496',
    projectId: 'event-app-m-2025',
    authDomain: 'event-app-m-2025.firebaseapp.com',
    storageBucket: 'event-app-m-2025.firebasestorage.app',
  );
}
